### PR TITLE
Allow to customize tag prefix (`--version-tag-prefix` option)

### PR DESCRIPTION
**Pull request by GethsLeader**
It's will be very useful feature for my current workplace project. Our CI/CD almost fully automated but our current script for version calculation is a kinda buggy, so I decided to switch it over this nx semver plugin (in this moment we are in the middle of refactoring our applications into nx mono repository) and actually this plugin is exactly what we need but it's missing critical for us feature - custom tag prefix. Our current pipelines are using additional information from tag for building process,  for example: we have 4 stages like development, qa, predproduction and production, and each of them can have different features and fixes sets that depends on what exactly was tested on previous stage, so when we building application it's going to be built with tags like `release/development/v1.71.188` or `release/qa/v1.69.50` to make sure that it will be deployed on right stage after mirroring into devops repository.

### CODE REVIEW

**Review by edbzn — CHANGES_REQUESTED** [review]
Hi, thanks a lot for this PR! That's a feature we thought about, and it's definitely a must-have. However, I would like to add support for a "magic string" to map the target name from the string option. For instance, if we pass `custom-prefix-$target-` then it would result in `custom-prefix-my-project-`. This would allow nice customization for the tag prefix. If you want to take it, go ahead, but if you are busy I can take it, let me know.

**Comment by GethsLeader** [comment]
> Hi, thanks a lot for this PR! That's a feature we thought about, and it's definitely a must-have. However, I would like to add support for a "magic string" to map the target name from the string option. For instance, if we pass `custom-prefix-$target-` then it would result in `custom-prefix-my-project-`. This would allow nice customization for the tag prefix. If you want to take it, go ahead, but if you are busy I can take it, let me know.

Hi, thank you for fast review ⚡
I'll do it. What do you think if I'll use [template string syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)? Like `custom-prefix-${target}-`?

**Comment by edbzn** [comment]
Perfect !

**Comment by GethsLeader** [comment]
> Perfect !

I guess it's ready: https://github.com/jscutlery/semver/pull/253/commits/399fd3a990f3fceee268f73a47147e1d83845d80

**Review by edbzn — APPROVED** [review]

**Comment by edbzn** [comment]
Thanks a lot for this work! It's in main now, I need to fix an issue before releasing it.

**Pull request closed without merging**
