### PR TITLE
feat: add support for standalone projects in a workspace without root config file

### LINKED ISSUE #600: feat: Add support for Nx project without a root configuration file (angular.json, workspace.json)
## The Problem

The latest versions of Nx (see [14.2.1](https://github.com/nrwl/nx/releases/tag/14.2.1)) support creating Nx workspace without an `angular.json`, `workspace.json` or `nx.json`.

However, when trying to run the `nx version <my-project>` in a workspace with that characteristic I get the following error.

` Error: ENOENT: no such file or directory, open '<path-to-my-project>/angular.json'`

## Acceptance Criteria

I should be able to use the version generator in a workspace with an `angular.json` file.

### PR DESCRIPTION
**Pull request by NachoVazquez**
## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, the Semver executor doesn't support a Nx workspace without a `workspace.json` or `angular.json`.

The project list is obtained from those files manually.

Fixes: #600 

## What is the new behavior?

The Semver executors support all kind of workspaces including workspaces without a root configuration file.

The list of projects is obtained from the `ContextExecutor->Workspace->ProjectsConfiguration.projects` property.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NachoVazquez** [comment]
I'm having an issue with a test, it is failing for me on the main.  But when I comment it out the `codecov` fails

**Comment by NachoVazquez** [comment]
As far as I understand this is completed. The CodeCov is failing for formatted lines.

**Comment by NachoVazquez** [comment]
@yjaaidi @edbzn could you take a look please?

**Comment by yjaaidi** [comment]
Hey @NachoVazquez,we'll check this out next week. 




Poke me if we dont 😅

**Comment by NachoVazquez** [comment]
Sure thing @yjaaidi , thanks!

**Comment by jamime** [comment]
@yjaaidi **bump** as requested.

**Comment by NachoVazquez** [comment]
All good friends @yjaaidi @jamime . This PR is ready again.

**Comment by edbzn** [comment]
Hi there, I'm back from holidays and will have a look at this soon. Thank you for the work @NachoVazquez!

**Comment by NachoVazquez** [comment]
I have fixed the merge conflicts @edbzn !

**Review by edbzn — APPROVED** [review]

**Comment by edbzn** [comment]
Thank you for the work @NachoVazquez!

**Pull request merged**
